print('INSTRUCTIONS:')
print('For each of the following grades, enter your score out of 100')
grade1 = float(input('    class engagement score:\n'))
grade2 = float(input('    zyBook Participation Activities score:\n'))
grade3 = float(input('    zyBook Challenge Activities score:\n'))
grade4 = float(input('    zyLab programming assignments score:\n'))
grade5 = float(input('    Blackboard programming assignments score:\n'))
grade6 = float(input('    midterm #1 score:\n'))
grade7 = float(input('    midterm #2 score:\n'))
grade8 = float(input('    final exam score:\n'))
print()
formula = (grade1 * 0.05) + (grade2 * 0.05) + (grade3 * 0.05) + (grade4 * 0.4)\
    + (grade5 * 0.15) + (grade6 * 0.1) + (grade7 * 0.1) + (grade8 * 0.1)
print(formula)
formula2 = formula
print('Your final grade for CSCE A101 is', f'{formula2:.2f}', end='')
print('%')
